mysql:
  image: mysql:5.6
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=admin
web:
  build: mage2cookbook-sample-docker
  ports:
    - "80:80"
  links:
    - mysql
  environment: 
    - MYSQL_USER=root
    - MYSQL_PASSWORD=admin
    - PUBLIC_HOST=mage2cookbook.com
